---
abstract: 'A port of ImgSeek to Perl'
author:
  - 'Helmut Wollmersdorfer <helmut.wollmersdorfer@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  ExtUtils::CppGuess: '0'
  Test::Exception: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
  ExtUtils::CppGuess: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150005'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Image-Seek
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006000'
resources:
  bugtracker: https://github.com/wollmers/Image-Seek/issues
  homepage: https://github.com/wollmers/Image-Seek
  repository: https://github.com/wollmers/Image-Seek.git
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
